codecov:
  require_ci_to_pass: false
  bot: null

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: 75% #overall project/ repo coverage

ignore:
  - "**/*Buyback*.sol"
